name: Assignment Workflow

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Setup Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      # >> This is where you would install any other dependencies you need <<
      - name: Install Testing Dependencies
        run: pip install -r tests/requirements.txt

      # >> This is where you would run your tests and generate the test-output.json file <<
      - name: Execute Tests
        run: python -m pytest --junitxml=test-output.xml
        continue-on-error: true

      - name: Install Dependencies for utilities
        run: |
          pip install requests
          npm install junit2json

      - name: Convert JUnitXML to JSON
        run: npx junit2json -p test-output.xml > test-output.json

      - name: Update Firestore with Test Results
        run: |
          branch_name=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          python workflow_utils/db_writer.py $branch_name test-output.json

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-output
          path: test-output.json
